# Generated by Django 3.2 on 2021-05-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infixation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infixation', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('youtube', 'other')], max_length=50)),
                ('vid_id', models.CharField(max_length=11)),
                ('comment_thread_id', models.CharField(max_length=11)),
                ('comment_id', models.CharField(max_length=11)),
            ],
        ),
    ]
