# Generated by Django 3.2 on 2021-05-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_builder', '0003_auto_20210502_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infixation',
            name='source',
            field=models.CharField(choices=[('youtube', 'other')], default=('youtube', 'other'), max_length=50),
        ),
    ]
