# Generated by Django 3.1.7 on 2021-06-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_builder', '0005_auto_20210523_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Checked_Vids',
            name='id',
        ),
        migrations.AlterField(
            model_name='Checked_Vids',
            name='vid_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
